gui:
  statusPanelView: allBranchesLog
git:
  # Command used to display git log of all branches in the main window.
  # Deprecated: Use `allBranchesLogCmds` instead.
  # allBranchesLogCmd: git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
  allBranchesLogCmd: git log --graph --all --color=always --pretty='format:%Cred%h %Cblue%an (%ad)%Cgreen%d %Creset%s' --date=relative
  paging:
    colorArg: always
    pager: delta --dark --paging=never --side-by-side

